"""added public id on tables

Revision ID: 5a72561cdf4b
Revises: c992663c64a3
Create Date: 2026-07-23 08:49:46.712326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a72561cdf4b'
down_revision: Union[str, Sequence[str], None] = 'c992663c64a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_public_id'), table_name='application')
    op.drop_column('application', 'public_id')
    op.drop_index(op.f('ix_candidate_public_id'), table_name='candidate')
    op.drop_column('candidate', 'public_id')
    op.drop_index(op.f('ix_vacancy_public_id'), table_name='vacancy')
    op.drop_column('vacancy', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('public_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_vacancy_public_id'), 'vacancy', ['public_id'], unique=True)
    op.add_column('candidate', sa.Column('public_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_candidate_public_id'), 'candidate', ['public_id'], unique=True)
    op.add_column('application', sa.Column('public_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_application_public_id'), 'application', ['public_id'], unique=True)
    # ### end Alembic commands ###
