"""Adicionado logica unica na tabela de Application

Revision ID: 5be1871b83e1
Revises: 4d5fa4a28e12
Create Date: 2026-08-08 22:15:11.955002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be1871b83e1'
down_revision: Union[str, Sequence[str], None] = '4d5fa4a28e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_candidate_vacancy', 'application', ['candidate_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_vacancy', 'application', type_='unique')
    # ### end Alembic commands ###
