"""increase resume_path and cpf size

Revision ID: 70f8a88f4f2c
Revises: c531712a73ae
Create Date: 2026-07-11 10:55:34.627841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f8a88f4f2c'
down_revision: Union[str, Sequence[str], None] = 'c531712a73ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'cpf',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.alter_column('candidate', 'resume_path',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'resume_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('candidate', 'cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
