"""create table vacancy and application

Revision ID: 888c2ccb4b49
Revises: 70f8a88f4f2c
Create Date: 2026-07-23 07:40:03.723126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '888c2ccb4b49'
down_revision: Union[str, Sequence[str], None] = '70f8a88f4f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_id'), 'vacancy', ['id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='candidatestatus'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_id'), 'application', ['id'], unique=False)
    op.add_column('candidate', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('candidate', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('candidate', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('candidate_cpf_key'), 'candidate', type_='unique')
    op.create_index(op.f('ix_candidate_cpf'), 'candidate', ['cpf'], unique=True)
    op.create_unique_constraint(None, 'candidate', ['email'])
    op.drop_column('candidate', 'status')
    op.drop_column('candidate', 'score')
    op.drop_column('candidate', 'vacancy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidate', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('candidate', sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='candidatestatus'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_index(op.f('ix_candidate_cpf'), table_name='candidate')
    op.create_unique_constraint(op.f('candidate_cpf_key'), 'candidate', ['cpf'], postgresql_nulls_not_distinct=False)
    op.drop_column('candidate', 'deleted_at')
    op.drop_column('candidate', 'email')
    op.drop_column('candidate', 'name')
    op.drop_index(op.f('ix_application_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_vacancy_id'), table_name='vacancy')
    op.drop_table('vacancy')
    # ### end Alembic commands ###
