"""modificado a tabela do application adicionando campo url

Revision ID: bded26df5f1c
Revises: 5be1871b83e1
Create Date: 2026-08-28 11:03:05.385834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bded26df5f1c'
down_revision: Union[str, Sequence[str], None] = '5be1871b83e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('resume_url', sa.String(length=255), nullable=False))
    op.add_column('candidate', sa.Column('resume_url', sa.String(length=255), nullable=False))
    op.drop_column('candidate', 'resume_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('resume_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('candidate', 'resume_url')
    op.drop_column('application', 'resume_url')
    # ### end Alembic commands ###
